services:
  my-project :
    container_name: bookkeeping
    image: bookkeeping-vue:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - /app/node_modules
    ports:
      - '8083:80'
