services:
  Bookkeeping :
    container_name: Bookkeeping
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - /app/node_modules
    ports:
      - '8083:80'
